version: '3'
services:
  db:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lucenelanches
    volumes:
      - data-volume:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - backend
  web:
    build: .
    command: java -jar target/lucenelanches-0.0.1-SNAPSHOT.jar
    volumes:
      - code-volume:/lucenelanches/
      - maven-repo:/root/.m2
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  data-volume:
  maven-repo:
  code-volume:
