insert into type_of_snack( description ) values ("normal");
insert into type_of_snack( description ) values ("model");
insert into type_of_bread (description, price) values ("Macio", 1);
insert into type_of_bread (description, price) values ("Duro", 2);
insert into cheese (description, price) values ("Provolone", 1);
insert into cheese (description, price) values ("Mussarela", 2);
insert into cheese (description, price) values ("Prato", 3);
insert into filling (description, price) values ("Bacon", 1);
insert into filling (description, price) values ("Ovo", 2);
insert into filling (description, price) values ("Milho", 1);
insert into salad (description, price) values ("lettuce", 1);
insert into salad (description, price) values ("arugula", 2);
insert into salad (description, price) values ("chard", 3);
insert into sauce (description, price) values ("italian", 1);
insert into sauce (description, price) values ("spicy", 2);
insert into spice (description, price) values ("chili", 1);
insert into spice (description, price) values ("salt", 2);
insert into spice (description, price) values ("oregano", 3);
insert into snack (cheese_id, filling_id, request_id, salad_id, type_id, type_of_bread_id, double_cheese, double_filling, double_salad) values (1, 1, null, 1, 2, 1, 0, 0, 0);
insert into snack (cheese_id, filling_id, request_id, salad_id, type_id, type_of_bread_id, double_cheese, double_filling, double_salad) values (2, 2, null, 2, 2, 2, 0, 0, 0);
insert into snack_sauces (snack_id, sauces_id) values (1, 1);
insert into snack_sauces (snack_id, sauces_id) values (1, 2);
insert into snack_sauces (snack_id, sauces_id) values (2, 1);
insert into snack_spices (snack_id, spices_id) values (1, 1);
insert into snack_spices (snack_id, spices_id) values (1, 3);
insert into snack_spices (snack_id, spices_id) values (2, 1);
insert into snack_spices (snack_id, spices_id) values (2, 2);
insert into rule(description) values ("ROLE_ADMIN");
insert into user(name, username, password) values ("Anderson Luis Ribeiro", "anderson", "$2a$06$QJi9vK.biSIcLKHIiEt9qeK7j/ZK7fGGzE5ZJ6upmcFfT.Q6MsegG");
insert into user(name, username, password) values ("Sofia Marini Ribeiro", "sofia", "$2a$06$QJi9vK.biSIcLKHIiEt9qeK7j/ZK7fGGzE5ZJ6upmcFfT.Q6MsegG");
insert into user_rules(user_id, rules_id) values (1, 1);
insert into user_rules(user_id, rules_id) values (2, 1);